#!/usr/bin/env sh

set -eu

main() {
	CheckTunnelAlreadyEstablished
	OpenBastionTunnel
}

CheckTunnelAlreadyEstablished() {
	if [ -f /var/run/bastion-brazilsouth.pid ] && netstat -tuln | grep -q 8222; then
		echo "Bastion tunnel to BrazilSouth is already running"
		exit 0
	fi
}

OpenBastionTunnel() {
	echo "Opening bastion tunnel to BrazilSouth..."

	az network bastion tunnel \
		--name hcs-bastion-service-brazilsouth \
		--resource-group rg-hcs-brazilsouth-dev \
		--target-resource-id "/subscriptions/1a8a30e4-894b-4f2c-9315-edb4fc5a31db/resourceGroups/rg-hcs-brazilsouth-dev/providers/Microsoft.Compute/virtualMachines/hcs-mgmt-vm-brazilsouth" \
		--resource-port 22 --port 8222 &
	echo $! > /tmp/bastion-brazilsouth.pid
}

main "$@"
